        @php
        $projects = [
        [
        'badge' => '1-2 спальни',
        'title' => 'BALCONY Naiyang',
        'price' => 'от 5.4 млн БАТ',
        'desc' => 'Balcony — Naiyang — курортный кондоминиум в тихом районе рядом с пляжем и международным аэропортом Пхукета. Проект сочетает близость к природе с современным комфортом и инвестиционной привлекательностью. Комплекс выполнен в стиле тропического курорта и предлагает зелёные зоны, бассейн и стиль лаунж общественные пространства, созданные для спокойного и расслабленного образа жизни.',
        'pdf' => 'assets/projects/pdf/13 The Balcony Naiyang.pdf',
        'images' => [
        'balcony-naiyang/1.jpg',
        'balcony-naiyang/2.jpg',
        'balcony-naiyang/3.jpg',
        'balcony-naiyang/4.jpg',
        'balcony-naiyang/5.jpg',
        'balcony-naiyang/6.jpg',
        'balcony-naiyang/7.jpg',
        'balcony-naiyang/8.jpg',
        'balcony-naiyang/9.jpg',
        'balcony-naiyang/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'VIBE RESIDENCE Karon',
        'price' => 'от 5.4 млн БАТ',
        'desc' => 'Vibe Residence — Karon — курортная роскошь всего в 200 метрах от пляжа в самом центре динамичного района Карон. Проект расположен в непосредственной близости от пляжа Карон, парка и самых оживлённых мест Пхукета, предлагая высокий уровень комфорта, удобства и приближённого образа жизни. Удобное транспортное сообщение с Патонгом и центром города.',
        'pdf' => 'assets/projects/pdf/19 Vibe Residence Karon.pdf',
        'images' => [
        'vibe-karon/1.jpg',
        'vibe-karon/2.jpg',
        'vibe-karon/3.jpg',
        'vibe-karon/4.jpg',
        'vibe-karon/5.jpg',
        'vibe-karon/6.jpg',
        'vibe-karon/7.jpg',
        'vibe-karon/8.jpg',
        'vibe-karon/9.jpg',
        'vibe-karon/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'HALO 1 Naiyang',
        'price' => 'от 5.13 млн БАТ',
        'desc' => 'The Halo 1 — Naiyang — курортный кондоминиум, сочетающий приватность, спокойствие и гармонию с природой. Зелёное окружение и продуманные общественные зоны создают атмосферу уединения и отдыха.
        Архитектура с характерными двускатными крышами и элегантным Skin Façade, вдохновлённым наследием Пхукета, объединяет современный дизайн и местный колорит.',
        'pdf' => 'assets/projects/pdf/1 HALO 1 Naiyang.pdf',
        'images' => [
        'HALO-Naiyang/1.jpg',
        'HALO-Naiyang/2.png',
        'HALO-Naiyang/3.jpg',
        'HALO-Naiyang/4.jpg',
        'HALO-Naiyang/5.jpg',
        'HALO-Naiyang/6.jpg',
        'HALO-Naiyang/7.jpg',
        'HALO-Naiyang/8.jpg',
        'HALO-Naiyang/9.jpg',
        'HALO-Naiyang/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'HERITAGE Bang-Tao',
        'price' => 'от 5.4 млн БАТ',
        'desc' => 'Heritage — Bang-Tao — курортный кондоминиум в престижном районе рядом с Boat Avenue, Porto de Phuket и Laguna Phuket, выполненный в современном стиле с сино-элементами.
        Развитая инфраструктура, близость пляжей Бангтао, Сурин и Лаян (5–10 минут) и удобный доступ к аэропорту Пхукета (около 35 минут) делают проект отличным выбором для жизни и инвестиций.',
        'pdf' => 'assets/projects/pdf/2 Heritage Bang-Tao.pdf',
        'images' => [
        'HERITAGE-BangTao/1.jpg',
        'HERITAGE-BangTao/2.jpg',
        'HERITAGE-BangTao/3.jpg',
        'HERITAGE-BangTao/4.jpg',
        'HERITAGE-BangTao/5.jpg',
        'HERITAGE-BangTao/6.jpg',
        'HERITAGE-BangTao/7.jpg',
        'HERITAGE-BangTao/8.jpg',
        'HERITAGE-BangTao/9.jpg',
        'HERITAGE-BangTao/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'LEGENDARY Bang-Tao',
        'price' => 'от 6.8 млн БАТ',
        'desc' => 'Legendary — Bang-Tao — современный жилой проект в престижном районе Бангтао, всего в нескольких минутах от пляжа и рядом с инфраструктурой и комплексом Laguna Phuket.
        Проект сочетает стильные интерьеры и более 35 удобств курортного уровня, включая бассейны, фитнес-центр, клубный дом, коворкинг и детские зоны, предлагая комфортный образ жизни и инвестиционную привлекательность.',
        'pdf' => 'assets/projects/pdf/3 Legendary Bang-Tao.pdf',
        'images' => [
        'LEGENDARY-BangTao/1.jpg',
        'LEGENDARY-BangTao/2.jpg',
        'LEGENDARY-BangTao/3.jpg',
        'LEGENDARY-BangTao/4.jpg',
        'LEGENDARY-BangTao/5.jpg',
        'LEGENDARY-BangTao/6.jpg',
        'LEGENDARY-BangTao/7.jpg',
        'LEGENDARY-BangTao/8.jpg',
        'LEGENDARY-BangTao/9.jpg',
        'LEGENDARY-BangTao/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'SERENITY Naiyang',
        'price' => 'от 3.4 млн БАТ',
        'desc' => 'Serenity — Naiyang — современный курортный кондоминиум рядом с аэропортом Пхукета и северными пляжами острова. Проект сочетает стильный дизайн, комфорт и удобное расположение.
        Комплекс предлагает развитую инфраструктуру для отдыха: бассейны, фитнес-центр, спа-зоны, онсэн и пространства для досуга. Пляж Найянг находится всего в 5 минутах, а рестораны, магазины и рынок — в шаговой доступности.',
        'pdf' => 'assets/projects/pdf/4 Serenity Naiyang.pdf',
        'images' => [
        'SERENITY-Naiyang/1.jpg',
        'SERENITY-Naiyang/2.jpg',
        'SERENITY-Naiyang/3.jpg',
        'SERENITY-Naiyang/4.jpg',
        'SERENITY-Naiyang/5.jpg',
        'SERENITY-Naiyang/6.jpg',
        'SERENITY-Naiyang/7.jpg',
        'SERENITY-Naiyang/8.jpg',
        'SERENITY-Naiyang/9.jpg',
        'SERENITY-Naiyang/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'MODEVA Bang-Tao',
        'price' => 'от 4.7 млн БАТ',
        'desc' => 'Modeva — Bang-Tao — стильный тропический проект с морской концепцией, где здания окружены извилистыми бассейнами и зелёным центральным пространством, создающим атмосферу уединённого острова.
        Комплекс предлагает курортную инфраструктуру, включая бассейны, фитнес, онсэн, коворкинг, детские и общественные зоны, и расположен в пешей доступности от пляжа Бангтао, что делает его привлекательным для жизни и инвестиций.',
        'pdf' => 'assets/projects/pdf/5 THE MODEVA Bang-Tao.pdf',
        'images' => [
        'MODEVA-BangTao/1.jpg',
        'MODEVA-BangTao/2.jpg',
        'MODEVA-BangTao/3.jpg',
        'MODEVA-BangTao/4.jpg',
        'MODEVA-BangTao/5.jpg',
        'MODEVA-BangTao/6.jpg',
        'MODEVA-BangTao/7.jpg',
        'MODEVA-BangTao/8.jpg',
        'MODEVA-BangTao/9.jpg',
        'MODEVA-BangTao/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'CIELO Rawai',
        'price' => 'от 4.8 млн БАТ',
        'desc' => 'Cielo — Rawai — премиальный прибрежный кондоминиум на юге Пхукета, в районе, известном своими живописными пейзажами и впечатляющими закатами. Раваи сочетает активный образ жизни с атмосферой уюта и аутентичного местного колорита.
        Проект гармонично объединяет современную архитектуру и природную красоту побережья, предлагая комфортное проживание и высокий инвестиционный потенциал.',
        'pdf' => 'assets/projects/pdf/6 Cielo Rawai.pdf',
        'images' => [
        'CIELO-Rawai/1.jpg',
        'CIELO-Rawai/2.jpg',
        'CIELO-Rawai/3.jpg',
        'CIELO-Rawai/4.jpg',
        'CIELO-Rawai/5.jpg',
        'CIELO-Rawai/6.jpg',
        'CIELO-Rawai/7.jpg',
        'CIELO-Rawai/8.jpg',
        'CIELO-Rawai/9.jpg',
        'CIELO-Rawai/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'ARTRIO BangTao',
        'price' => 'от 4.3 млн БАТ',
        'desc' => 'Artrio — Bang-Tao — проект надёжного застройщика в самом центре Бангтао, рядом с Porto de Phuket, Boat Avenue и комплексом Laguna Phuket.
        Проект предлагает современные резиденции с продуманными планировками и подходит как для комфортного проживания, так и для инвестиций. Вся ключевая инфраструктура находится в шаговой доступности, а пляжи Бангтао, Сурин и Лаян — всего в 10 минутах.',
        'pdf' => 'assets/projects/pdf/7 Artrio Bang-Tao.pdf',
        'images' => [
        'ARTRIO-BangTao/1.png',
        'ARTRIO-BangTao/2.jpg',
        'ARTRIO-BangTao/3.jpg',
        'ARTRIO-BangTao/4.jpg',
        'ARTRIO-BangTao/5.jpg',
        'ARTRIO-BangTao/6.jpg',
        'ARTRIO-BangTao/7.jpg',
        'ARTRIO-BangTao/8.jpg',
        'ARTRIO-BangTao/9.png',
        'ARTRIO-BangTao/10.png',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'KATABELLO Kata',
        'price' => 'от 4.2 млн БАТ',
        'desc' => 'Katabello — Kata — курортный кондоминиум в центре Каты с развитой инфраструктурой и условиями для проживания с домашними животными.
        Комплекс окружён бассейнами в стиле каналов и предлагает лаунж-зоны, кафе и специализированную pet-friendly инфраструктуру. Удобное расположение делает проект привлекательным как для комфортной жизни, так и для арендных инвестиций.',
        'pdf' => 'assets/projects/pdf/8 The Katabello Kata.pdf',
        'images' => [
        'KATABELLO-Kata/1.jpg',
        'KATABELLO-Kata/2.jpg',
        'KATABELLO-Kata/3.jpg',
        'KATABELLO-Kata/4.jpg',
        'KATABELLO-Kata/5.jpg',
        'KATABELLO-Kata/6.jpg',
        'KATABELLO-Kata/7.jpg',
        'KATABELLO-Kata/8.jpg',
        'KATABELLO-Kata/9.jpg',
        'KATABELLO-Kata/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'ADORA Rawai',
        'price' => 'от 5.3 млн БАТ',
        'desc' => 'Adora — Rawai — современный тропический проект с акцентом на комфорт, приватность и функциональные планировки.
        Расположен на юге Пхукета, рядом с пляжами Раваи и Най Харн и ключевыми локациями района, что делает проект подходящим как для жизни, так и для инвестиций с хорошим арендным потенциалом.
        Проект идеален для спокойного проживание.',
        'pdf' => 'assets/projects/pdf/9 Adora Rawai.pdf',
        'images' => [
        'adora-rawai/1.jpg',
        'adora-rawai/2.jpg',
        'adora-rawai/3.jpg',
        'adora-rawai/4.jpg',
        'adora-rawai/5.jpg',
        'adora-rawai/6.jpg',
        'adora-rawai/7.jpg',
        'adora-rawai/8.jpg',
        'adora-rawai/9.jpg',
        'adora-rawai/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'SIERRA Bang-Tao',
        'price' => 'от 2.9 млн БАТ',
        'desc' => 'Sierra — Bang-Tao — современный жилой проект от надёжного застройщика в центре Ченг Талей, рядом с Porto de Phuket, Boat Avenue и комплексом Laguna Phuket.
        Проект предлагает курортную инфраструктуру, включая бассейн на крыше, фитнес-центр, коворкинг, pet-зону и круглосуточную охрану. Пляжи Бангтао, Сурин и Лаян находятся в 10–15 минутах , а аэропорт Пхукета — в 35 минутах.',
        'pdf' => 'assets/projects/pdf/10 Sierra Bang-Tao.pdf',
        'images' => [
        'SIERRA-BangTao/1.png',
        'SIERRA-BangTao/2.jpg',
        'SIERRA-BangTao/3.png',
        'SIERRA-BangTao/4.png',
        'SIERRA-BangTao/5.png',
        'SIERRA-BangTao/6.png',
        'SIERRA-BangTao/7.png',
        'SIERRA-BangTao/8.png',
        'SIERRA-BangTao/9.png',
        'SIERRA-BangTao/10.jpeg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'VILLA KIRARA Bang-Tao',
        'price' => 'от 29 млн БАТ',
        'desc' => 'Villa Kirara — Bang-Tao — современный проект вилл с частными бассейнами, расположенный в тихом предгорном районе Ченг Талей, рядом с HeadStart International School, Boat Avenue, Laguna Phuket и пляжами Бангтао, Сурин и Лаян.
        Проект из 37 стильных вилл с частными бассейнами и озеленёнными территориями. Спокойная атмосфера и удобная локация это отличный выбор для семейного отдыха и инвестиций.',
        'pdf' => 'assets/projects/pdf/11 Villa Kirara Bang-Tao.pdf',
        'images' => [
        'VILLA-KIRARA-Bang-Tao/1.jpeg',
        'VILLA-KIRARA-Bang-Tao/2.jpeg',
        'VILLA-KIRARA-Bang-Tao/3.jpeg',
        'VILLA-KIRARA-Bang-Tao/4.jpeg',
        'VILLA-KIRARA-Bang-Tao/5.jpeg',
        'VILLA-KIRARA-Bang-Tao/6.jpeg',
        'VILLA-KIRARA-Bang-Tao/7.jpeg',
        'VILLA-KIRARA-Bang-Tao/8.jpeg',
        'VILLA-KIRARA-Bang-Tao/9.jpeg',
        'VILLA-KIRARA-Bang-Tao/10.jpg',
        ],
        ],
        [
        'badge' => '1-2 спальни',
        'title' => 'CORALINA Kamala',
        'price' => 'от 4.7 млн БАТ',
        'desc' => 'Coralina — Kamala — современный pet-friendly кондоминиум в престижном районе Камала, всего в 10 минутах от пляжа. Проект подходит как для проживания, так и для инвестиций.
        Комплекс располагает курортной инфраструктурой: бассейнами, фитнес и йога-зонами, спа, детскими и pet-зонами, коворкингом и круглосуточной охраной. Удобное расположение обеспечивает быстрый доступ к центру Камалы, Патонгу и комплексу Laguna Phuket.',
        'pdf' => 'assets/projects/pdf/12 Coralina Kamala.pdf',
        'images' => [
        'CORALINA-Kamala/1.jpg',
        'CORALINA-Kamala/2.jpg',
        'CORALINA-Kamala/3.jpg',
        'CORALINA-Kamala/4.jpg',
        'CORALINA-Kamala/5.jpg',
        'CORALINA-Kamala/6.jpg',
        'CORALINA-Kamala/7.jpg',
        'CORALINA-Kamala/8.jpg',
        'CORALINA-Kamala/9.jpg',
        'CORALINA-Kamala/10.jpeg',
        ],
        ],
        ];
        @endphp










                @php
        $projects = [
        [
        'badge_key' => 'projects.badge_1_2_bed',
        'title' => 'BALCONY Naiyang',
        'price_key' => 'projects.price_balcony',
        'desc_key' => 'projects.desc_balcony',
        'pdf' => 'assets/projects/pdf/13 The Balcony Naiyang.pdf',
        'images' => [
        'balcony-naiyang/1.jpg',
        'balcony-naiyang/2.jpg',
        'balcony-naiyang/3.jpg',
        'balcony-naiyang/4.jpg',
        'balcony-naiyang/5.jpg',
        'balcony-naiyang/6.jpg',
        'balcony-naiyang/7.jpg',
        'balcony-naiyang/8.jpg',
        'balcony-naiyang/9.jpg',
        'balcony-naiyang/10.jpg',
        ],
        ],
        [
        'badge_key' => 'projects.badge_1_2_bed',
        'title' => 'VIBE RESIDENCE Karon',
        'price_key' => 'projects.price_vibe-karon',
        'desc_key' => 'projects.desc_vibe-karon',
        'pdf' => 'assets/projects/pdf/19 Vibe Residence Karon.pdf',
        'images' => [
        'vibe-karon/1.jpg',
        'vibe-karon/2.jpg',
        'vibe-karon/3.jpg',
        'vibe-karon/4.jpg',
        'vibe-karon/5.jpg',
        'vibe-karon/6.jpg',
        'vibe-karon/7.jpg',
        'vibe-karon/8.jpg',
        'vibe-karon/9.jpg',
        'vibe-karon/10.jpg',
        ],
        ],
        ];
        @endphp